---
- name: Install Apache and Upload my Web Page
  hosts: reserv
  become: yes

  vars:
    source_file: ./Zakaz1
    destin_file: /var/www/

  tasks:
  - name: Install Apache Web Server
    apt: name=apache2 state=latest

  - name: Copy MyHomePage to Servers
    copy: src={{ source_file}} dest={{ destin_file}} mode=0555
    notify: Restart Apache

  - name: Start Web Server and make it enable on boot
    service: name=apache2 state=started enabled=yes

  - name: Install php
    apt: name=libapache2-mod-php state=latest

  handlers:
  - name: Restart Apache
    service: name=apache2 state=restarted

